[package]
name = "rvemu"
version = "0.1.0"
edition = "2021"

#[features]
#std = ["num-traits/std"]

[dependencies]
#num-traits = { version = "0.2", default-features = false, features = [], optional = true }
num-traits = {version = "0.2"}
